FROM golang:1.23-alpine AS builder

WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /scenarioengine ./cmd/scenario/

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /scenarioengine /usr/bin/scenarioengine
ENTRYPOINT ["/usr/bin/scenarioengine"]
