FROM golang:1.23-alpine AS builder

WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /scoreboard ./cmd/scoreboard/

FROM alpine:3.19
RUN apk add --no-cache ca-certificates curl
COPY --from=builder /scoreboard /usr/bin/scoreboard
COPY scoreboard/web /web
ENTRYPOINT ["/usr/bin/scoreboard"]
