# WireGuard server config for the Viceroy practice range.
# Generated by scripts/wg-gen.sh — do not edit the generated server.conf
# directly; re-run the generator instead.
#
# The server interface is 10.8.0.1/24. Team members connect as peers on
# 10.8.0.2, 10.8.0.3, ... and reach the range at 10.8.0.1 (attack-station
# SSH + scoreboard).

[Interface]
PrivateKey = {{SERVER_PRIVKEY}}
Address = 10.8.0.1/24
ListenPort = {{SERVER_PORT}}
# Optional: hardened defaults. Uncomment if your kernel/wg-quick supports them.
# SaveConfig = false
# MTU = 1420

# Peers follow — one block per team member.
{{PEER_BLOCKS}}
